package com.kapcode.open.macropad.kmps.ui.theme

import androidx.compose.ui.graphics.Color

// Light Blue Theme Colors
val light_primary = Color(0xFF0061A4)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFD1E4FF)
val light_onPrimaryContainer = Color(0xFF001D36)
val light_secondary = Color(0xFF535F70)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD7E3F8)
val light_onSecondaryContainer = Color(0xFF101C2B)
val light_tertiary = Color(0xFF6B5778)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFF3DAFF)
val light_onTertiaryContainer = Color(0xFF251432)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_background = Color(0xFFFDFCFF)
val light_onBackground = Color(0xFF1A1C1E)
val light_surface = Color(0xFFFDFCFF)
val light_onSurface = Color(0xFF1A1C1E)
val light_surfaceVariant = Color(0xFFDFE2EB)
val light_onSurfaceVariant = Color(0xFF43474E)
val light_outline = Color(0xFF73777F)

// Dark Blue Theme Colors
val dark_primary = Color(0xFF9ECAFF)
val dark_onPrimary = Color(0xFF003258)
val dark_primaryContainer = Color(0xFF00497D)
val dark_onPrimaryContainer = Color(0xFFD1E4FF)
val dark_secondary = Color(0xFFBBC7DB)
val dark_onSecondary = Color(0xFF253141)
val dark_secondaryContainer = Color(0xFF3B4858)
val dark_onSecondaryContainer = Color(0xFFD7E3F8)
val dark_tertiary = Color(0xFFD7BDE4)
val dark_onTertiary = Color(0xFF3B2948)
val dark_tertiaryContainer = Color(0xFF523F5F)
val dark_onTertiaryContainer = Color(0xFFF3DAFF)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_background = Color(0xFF1A1C1E)
val dark_onBackground = Color(0xFFE2E2E6)
val dark_surface = Color(0xFF1A1C1E)
val dark_onSurface = Color(0xFFE2E2E6)
val dark_surfaceVariant = Color(0xFF43474E)
val dark_onSurfaceVariant = Color(0xFFC3C7CF)
val dark_outline = Color(0xFF8D9199)
